[workspace]
channels = ["conda-forge"]
name = "NeuralNetworkClassifier"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]

[dependencies]
numpy = ">=2.2.4,<3"
tensorflow = ">=2.18.0,<3"
keras = ">=3.9.0,<4"
matplotlib = ">=3.10.1,<4"
pandas = ">=2.2.3,<3"
pyreadr = ">=0.5.3,<0.6"
scikit-learn = "1.5.0.*"
joblib = ">=1.4.2,<2"
